### ISSUE TITLE
NoSuchMethodError: The method 'toDouble' was called on null

### ISSUE THREAD

**Issue by jcowgar** [arabbani/unit_converter#12]
After adding unit_converter to my project:

```
dependencies:
  unit_converter: ^1.1.0
```

and running 

```
$ pub get
```

and creating a sample application:

```
import 'package:unit_converter/unit_converter.dart';

main() {
  var areaConverter = getConverter(Converter.area);
  areaConverter.convert(
    value: 2,
    from: AreaUnit.acre,
    to: AreaUnit.squareFoot,
  );
}
```

and running the application:

```
pub run example/ut_test.dart
```

I get:

```
Unhandled exception:
NoSuchMethodError: The method 'toDouble' was called on null.
Receiver: null
Tried calling: toDouble()
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      double.* (dart:core-patch/double.dart:36:23)
#2      UnitConverter.convert (package:unit_converter/src/converter/unit_converter.dart:50:17)
#3      main (file:///C:/Users/jerem/projects/dart/ballooning/example/ut_test.dart:5:17)
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by arabbani** [comment]
Looking into the problem

**Comment by jcowgar** [comment]
Any findings?

**Comment by glozano** [comment]
I'm having the same issue trying to do any conversion or just trying to get the units from a converter

**Comment by ptsd** [comment]
Unit initialisation seems to depend on other units, it gets halfway though initialising acceleration and then tries to use _hourToSecond which relies on Converter.time being initialised.

**Comment by austin-zy** [comment]
Is it intended that all the key-value pairs in `lib/src/constant/others/conversion_factors.dart` has empty values?

**Comment by arabbani** [comment]
Sorry for the late reply. I will look at it tonight

**Comment by runedrune** [comment]
Hey any update regarding this?

**Comment by Kleak** [comment]
Hi got the same error

**Comment by arabbani** [comment]
Hi guys, Actually I'm not working on the repo anymore.

**Comment by arabbani** [comment]
I'll mark it as deprecated

**Comment by arabbani** [comment]
Sorry guys.

**Comment by arabbani** [comment]
Hi guys,
I have fixed the issue. Can you guys please try once. I know my response to the issue is very late. Please check once in your project with the latest version.
Please feel free to reply back. Again sorry for the late reply.

Thanks,
Arif Rabbani

**Comment by Junaidhassan99** [comment]
I am getting the same error version: 1.3
