### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by Miamoto-Musashi** [arabbani/unit_converter#15]
I receive this error during compile time

```
Running Gradle task 'assembleDebug'...
../../../.pub-cache/hosted/pub.dartlang.org/unit_converter-1.2.0/lib/src/converters/unit_converter.dart:23:16: Error: Can't access 'this' in a field initializer to read '_baseUnit'.
        assert(_baseUnit != null) {
               ^^^^^^^^^

```

**Comment by arabbani** [comment]
This is happening because I'm trying to access this reference in an initializer block and according to dart doc, the right hand side of the initializer does not have access to this.

Thanks for your interest in the library.

**Comment by Miamoto-Musashi** [comment]
Yes during initialization you don't have the object yet so `this` is not available
